# .github/workflows/autograding.yml
name: Autograding Tests
on:
  push: { }
  repository_dispatch: { }

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    container:
      image: python:3.12  # Running inside a Python container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repository
        uses: actions/checkout@v4

      # New step: checkout the secret tests from a separate repository.
      - name: Checkout secret tests repository
        uses: actions/checkout@v4
        with:
          repository: top-secret-ucb-urban-informatics/secret-tests
          token: ${{ secrets.SECRET_TESTS_TOKEN }}  # PAT with access to the secret repo.
          path: secret  # This will place the secret tests in "./test"

      - name: Install dependencies (git, nodejs, check50)
        run: |
          apt-get update
          apt-get install -y git nodejs npm
          python -m pip install --upgrade pip setuptools wheel check50

      - name: Install the Python project
        run: |
          python -m pip install .

      - name: Test
        id: test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test
          setup-command: |
            pip uninstall -y check50
            pip install --no-cache-dir git+https://github.com/dhodcz2/check50.git
          command: check50 ./secret/test --dev -o json --autograder ./autograder/test.json --feedback ./feedback/test.txt

      - name: Assign file contents to TEST_RESULTS
        run: |
          echo "TEST_RESULTS=$(base64 -w0 ./autograder/test.json)" >> $GITHUB_ENV

      - name: Feedback
        if: ${{ always() }}
        run: |
          echo "### Feedback Output:"
          cat ./feedback/test.txt
        continue-on-error: true

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST_RESULTS: ${{ env.TEST_RESULTS }}
        with:
          runners: test
